# 1. Extracción de datos

Conectaremos una fuente a la vez y convertiremos los resultados en DataFrames.

In [1]:
from pathlib import Path
import sys

BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(BASE_DIR))

In [6]:
from src.extraccion import  MongoDBExtractor

extractor_ = MongoDBExtractor()

extractor_.connect()

DATOS_ARBNB = extractor_.extract_all_collections()

DATOS_ARBNB["calendar"].head()

DATOS_ARBNB["reviews"].head()

DATOS_ARBNB["listing"].head()

,_id,listing_id,date,available,minimum_nights,maximum_nights
0,6ac8f34b9ec0a88371ee9b24,15410909,2026-06-22,False,2,1125
1,6ac8f34b9ec0a88371ee9b25,15410909,2026-06-23,False,2,1125
2,6ac8f34b9ec0a88371ee9b26,15410909,2026-06-24,False,2,1125
3,6ac8f34b9ec0a88371ee9b27,15410909,2026-06-25,True,2,1125
4,6ac8f34b9ec0a88371ee9b28,15410909,2026-06-26,True,2,1125

In [5]:
print("dimesiones del liting", DATOS_ARBNB["listing"].shape)
print("dimesiones del calendar", DATOS_ARBNB["calendar"].shape)
print("dimesiones del reviews", DATOS_ARBNB["reviews"].shape)

dimesiones del liting (19187, 79)
dimesiones del calendar (7003255, 6)
dimesiones del reviews (527731, 7)

In [10]:
DATOS_ARBNB["listing"].info()

<class 'pandas.DataFrame'>
RangeIndex: 19187 entries, 0 to 19186
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   _id                                           19187 non-null  object
 1   id                                            19187 non-null  int64
 2   listing_url                                   19187 non-null  str
 3   scrape_id                                     19187 non-null  int64
 4   last_scraped                                  19187 non-null  datetime64[us]
 5   source                                        19187 non-null  str
 6   name                                          19187 non-null  object
 7   description                                   18664 non-null  str
 8   picture_url                                   19187 non-null  str
 9   host_id                                       19187 non-null  int64
 10  host_url                                      19187 non-null  str
 11  host_profile_id                               19187 non-null  int64
 12  host_profile_url                              19187 non-null  str
 13  host_name                                     19187 non-null  str
 14  hosts_time_as_user_years                      19187 non-null  int64
 15  hosts_time_as_user_months                     19187 non-null  int64
 16  hosts_time_as_host_years                      19186 non-null  float64
 17  hosts_time_as_host_months                     19186 non-null  float64
 18  host_location                                 14030 non-null  str
 19  host_about                                    10388 non-null  object
 20  host_is_superhost                             19187 non-null  bool
 21  host_picture_url                              19187 non-null  str
 22  host_listings_count                           19187 non-null  int64
 23  host_verifications                            19187 non-null  str
 24  host_has_profile_pic                          19187 non-null  bool
 25  host_identity_verified                        19187 non-null  bool
 26  neighbourhood_cleansed                        19187 non-null  str
 27  latitude                                      19187 non-null  float64
 28  longitude                                     19187 non-null  float64
 29  property_type                                 19187 non-null  str
 30  room_type                                     19187 non-null  str
 31  accommodates                                  19187 non-null  int64
 32  bathrooms_text                                19158 non-null  str
 33  bedrooms                                      16228 non-null  float64
 34  beds                                          18896 non-null  float64
 35  amenities                                     19187 non-null  object
 36  price                                         18992 non-null  str
 37  price_quote_checkin_date                      19184 non-null  datetime64[us]
 38  price_quote_checkout_date                     19184 non-null  datetime64[us]
 39  price_quote_total_price                       18992 non-null  float64
 40  price_quote_price_per_night                   18992 non-null  float64
 41  price_quote_raw                               19184 non-null  object
 42  minimum_nights                                19183 non-null  float64
 43  maximum_nights                                19183 non-null  float64
 44  minimum_minimum_nights                        19183 non-null  float64
 45  maximum_minimum_nights                        19183 non-null  float64
 46  minimum_maximum_nights                        19183 non-null  float64
 47  maximum_maximum_nights                        19183 non-null  float64
 48  minimum_nights_avg_ntm                        19187 non-null  float64
 49  maximum_nights_avg_ntm                        19187 non-null  float64
 50  has_availability                              19057 non-null  object
 51  availability_30                               19187 non-null  int64
 52  availability_60                               19187 non-null  int64
 53  availability_90                               19187 non-null  int64
 54  availability_365                              19187 non-null  int64
 55  calendar_last_scraped                         19187 non-null  datetime64[us]
 56  number_of_reviews                             19187 non-null  int64
 57  number_of_reviews_ltm                         19187 non-null  int64
 58  number_of_reviews_l30d                        19187 non-null  int64
 59  availability_eoy                              19187 non-null  int64
 60  number_of_reviews_ly                          19187 non-null  int64
 61  estimated_occupancy_l365d                     19187 non-null  int64
 62  estimated_revenue_l365d                       18980 non-null  float64
 63  first_review                                  14922 non-null  datetime64[us]
 64  last_review                                   14922 non-null  datetime64[us]
 65  review_scores_rating                          14922 non-null  float64
 66  review_scores_accuracy                        14922 non-null  float64
 67  review_scores_cleanliness                     14922 non-null  float64
 68  review_scores_checkin                         14921 non-null  float64
 69  review_scores_communication                   14922 non-null  float64
 70  review_scores_location                        14921 non-null  float64
 71  review_scores_value                           14921 non-null  float64
 72  license                                       16255 non-null  float64
 73  calculated_host_listings_count                19187 non-null  int64
 74  calculated_host_listings_count_entire_homes   19187 non-null  int64
 75  calculated_host_listings_count_private_rooms  19187 non-null  int64
 76  calculated_host_listings_count_shared_rooms   19187 non-null  int64
 77  reviews_per_month                             14922 non-null  float64
 78  bathrooms                                     18121 non-null  float64
dtypes: bool(3), datetime64[us](6), float64(27), int64(22), object(6), str(15)
memory usage: 11.2+ MB

In [16]:
# Definimos la variable df_listing usando la colección extraída
df_listing = DATOS_ARBNB["listing"]

# Y luego ya puedes ejecutar el bloque de estadísticas descriptivas:
columnas_relevantes = [col for col in ['price_quote_total_price', 'minimum_nights', 'availability_365', 'number_of_reviews'] if col in df_listing.columns]

if columnas_relevantes:
    display(df_listing[columnas_relevantes].describe())
else:
    display(df_listing.describe(include=['number', 'float', 'int']))

,price_quote_total_price,minimum_nights,availability_365,number_of_reviews
count,1.899200e+04,19183.000000,19187.000000,19187.000000
mean,1.934169e+06,6.979878,306.947725,27.504612
std,6.194073e+07,10.993985,82.073601,74.004586
min,2.800000e+04,1.000000,0.000000,0.000000
25%,1.688988e+05,1.000000,269.000000,1.000000
50%,3.033605e+05,1.000000,349.000000,8.000000
75%,8.894161e+05,3.000000,363.000000,31.000000
max,8.401451e+09,32.000000,365.000000,6162.000000

#  ANALISIS DE LA INFORMACION

El análisis exploratorio de la variable de precios 
(price_quote_total_price) evidencia la presencia de valores 
atípicos severos (outliers) con máximos erróneos de hasta 
8.4 mil millones de pesos, lo que hace indispensable aplicar un 
filtro de limpieza y acotación de precios en la fase de transformación del pipeline 
ETL para evitar sesgos analíticos.